// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOoOq0msuz4kJEVvFLbbF8Ni1KcvQ_JFg',
    appId: '1:1096898407302:web:9816bbe211bb1bf16a1a07',
    messagingSenderId: '1096898407302',
    projectId: 'dudu-53b60',
    authDomain: 'dudu-53b60.firebaseapp.com',
    storageBucket: 'dudu-53b60.appspot.com',
    measurementId: 'G-S0L5QBSBYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPg4_mwJuQudwOFHwCvef-0KhSqFbQZM',
    appId: '1:1096898407302:android:57f8e636ef00cb6b6a1a07',
    messagingSenderId: '1096898407302',
    projectId: 'dudu-53b60',
    storageBucket: 'dudu-53b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZkEAmzKTtf-vo2Lo8UQ-RVkfKj7Z85Kg',
    appId: '1:1096898407302:ios:6541a9b631e6d3396a1a07',
    messagingSenderId: '1096898407302',
    projectId: 'dudu-53b60',
    storageBucket: 'dudu-53b60.appspot.com',
    iosBundleId: 'com.obeyinternational.dudu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZkEAmzKTtf-vo2Lo8UQ-RVkfKj7Z85Kg',
    appId: '1:1096898407302:ios:6541a9b631e6d3396a1a07',
    messagingSenderId: '1096898407302',
    projectId: 'dudu-53b60',
    storageBucket: 'dudu-53b60.appspot.com',
    iosBundleId: 'com.obeyinternational.dudu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOoOq0msuz4kJEVvFLbbF8Ni1KcvQ_JFg',
    appId: '1:1096898407302:web:538c8e1c29e428196a1a07',
    messagingSenderId: '1096898407302',
    projectId: 'dudu-53b60',
    authDomain: 'dudu-53b60.firebaseapp.com',
    storageBucket: 'dudu-53b60.appspot.com',
    measurementId: 'G-JNWS5MG4E8',
  );
}
